### ISSUE TITLE
React native Webview not working on iOS 13

### ISSUE THREAD

**Issue by cleandersonlobo** [talkjs/talkjs-examples#288]
The chat works in my simulator 15+, but when I tested it on a device with iOS 13.4, it just didn't work.

After reading this page https://talkjs.com/docs/Getting_Started/

I manually changed this method in the WebView.js file

```javascript
try {
   await Talk.ready;
....
} catch {}
```

for this ...

```javascript

Talk.ready.then(() => {....})
```

**And, it worked!**
 
Where can I update this in `@talkjs/react-native`?

Can someone help me?

**Comment by cleandersonlobo** [comment]
Thanks @eteeselink 

Sugestão. Deveria ser adicionado novos props do Webview que faz muito sentindo. 

```
startInLoadingState
renderLoading
onLoadEnd
onError
```

**Comment by vickz84259** [comment]
Hey, I'm Victor, a developer at TalkJS. I just wanted to let you know that we have released a fix for the issue you highlighted. Do upgrade to version 0.3.3 of the SDK. 

Thank you for bringing this issue to our attention. Should you have any other issues with the SDK feel free to create a separate issue or notify us via our [livesupport](https://talkjs.com/?chat).

Regarding the props you suggested, we are discussing it internally.
