### ISSUE TITLE
Flutter SDK always loading in flutter module

### ISSUE THREAD

**Issue by norman93sun** [talkjs/talkjs-examples#442]
I created a flutter Module, add talkJs flutter SDK. things are alright when I run module simply.
After that I mixed the flutter Module to my iOS project, when I start talkjs screen it always show loading, that loading took a long time before it disappear.

<img width="297" alt="截屏2023-09-14 17 16 51" src="https://github.com/talkjs/talkjs-examples/assets/18303855/f1f5910b-7a16-4c30-872d-e6b03f5764ef">
<img width="318" alt="截屏2023-09-14 17 18 15" src="https://github.com/talkjs/talkjs-examples/assets/18303855/050e5884-82c1-42f2-befe-54ff4e45b16a">

The way I integrated a Flutter module into my iOS project

<img width="895" alt="截屏2023-09-14 17 36 11" src="https://github.com/talkjs/talkjs-examples/assets/18303855/9dc69275-5495-4da2-8576-c0c28a3d4926">

**Comment by MattivdWeem** [comment]
Hey @norman93sun, 

Could you share a bit more information about your implementation? E.G. what does the code look like and the package version you're using. It would also be great if you could information from the network debugging tab and if you got any errors showing up in your debug console.

Feel free to reach out via [the chat on our site ](https://talkjs.com/?chat) it's staffed by our engineering team and we usually reply a bit faster over there.

**Comment by norman93sun** [comment]
Hi @MattivdWeem,
Everything is ok today, but nothing changed. I dont known what is the problem.

I will close this issue

**Comment by norman93sun** [comment]
Found the issue, network conditions can affect loading.
It works smoothly since I open my VPN

**Comment by MattivdWeem** [comment]
Hi @norman93sun,

Glad to hear it's working! Could you share a HAR file or a rundown of the network requests and their status with your VPN disabled? I'm interested in pinpointing any potential blockers, given that the UI seems to have loaded correctly. This info might help us explore options like adding CDN locations.

**Comment by norman93sun** [comment]
Hi @MattivdWeem,

Hope this file will help you.

[talkjs.har.zip](https://github.com/talkjs/talkjs-examples/files/12657433/talkjs.har.zip)
