### ISSUE TITLE
[React native] Error: conversationBuilder._setInjectJavaScript is not a function (it is undefined)

### ISSUE THREAD

**Issue by cesardoorvel** [talkjs/talkjs-examples#446]
## Description
I am playing [the example](https://github.com/talkjs/talkjs-examples/tree/master/react-native/basic-example/ReactNativeNavigationExample) of this repo using a fresh project.  Everythin works almost okay except for the following error 
![image](https://github.com/talkjs/talkjs-examples/assets/146477702/35a8e9a7-0688-43db-bbf4-39b02877f00a)

It happens when I press the conversation item from the list:

![image](https://github.com/talkjs/talkjs-examples/assets/146477702/ca044b18-bf9f-464f-bd13-6b97c0c18f61)

## Steps to reproduce the error

![talkjs-error](https://github.com/talkjs/talkjs-examples/assets/146477702/89a4f240-a5d8-4723-800e-5d76464f7e69)

## Dependencies

@notifee/react-native: "^7.8.0"
@react-native-async-storage/async-storage: "^1.19.3"
@react-native-community/push-notification-ios: "^1.11.0"
@react-native-firebase/app: "^18.5.0"
@react-native-firebase/messaging: "^18.5.0"
@react-navigation/native: "^6.1.8"
@talkjs/react-native: "^0.6.0"
react: "18.2.0"
react-native: "0.72.5"
react-native-navigation: "^7.37.0-hotfix.1"
react-native-safe-area-context: "^4.7.2"
react-native-screens: "^3.25.0"
react-native-webview: "^13.6.0"

Can you guys please help me?

NOTE: I have downgraded @talkjs/react-native to 0.5.1 and it works

**Comment by Joshmatjjen** [comment]
@cesardoorvel  Please reopen this issue... it need to be resolved.  Downgrading is not the solution

**Comment by blogui91** [comment]
@Joshmatjjen I am sorry.  I closed it because there is a new version where this error was fixed.
