### ISSUE TITLE
Button Actions

### ISSUE THREAD

**Issue by prachipatel01** [talkjs/talkjs-examples#545]
Hey, 
I am building a chat application using talkjs react-native sdk.  The react-native SKD is really awesome. The only issue I am facing is to add custom actions on custom button in the UI. I went through the whole documentation but couldn't find a way to add custom actions.

Can you please help me with how to do that?
I really appreciate any help you can provide.

**Comment by vickz84259** [comment]
Hey, my name is Victor. I'm a developer here at TalkJS. To add custom actions you do that through the Theme Editor on the TalkJS [dashboard](https://talkjs.com/dashboard). You can read more about them here: https://talkjs.com/docs/Features/Customizations/Action_Buttons_Links/

**Comment by vickz84259** [comment]
Once you've modified your theme to your liking, you can add that theme to a specific role then assign that role to a user or you can even override the theme directly through the [theme prop](https://talkjs.com/docs/Reference/React_Native_SDK/Components/Chatbox/#theme) on either the Chatbox or ConversationList components.

**Comment by prachipatel01** [comment]
Hey Victor, thanks for your prompt response. 

I tried your approach but my use case is different. I want an action to occur when the user clicks on a specific UI component (not necessarily a button). For example, I have a custom message component that contains an image, now when the user clicks on this image I want certain actions(for example, navigating to a different screen) to be performed.

**Comment by prachipatel01** [comment]
Hey,
Thanks to talkjs support team, I got a solution for my use case. I can wrap the image around ActionLink and trigger any action I want.
