### ISSUE TITLE
Dart code samples

### ISSUE THREAD

**Issue by ashwin31** [talkjs/talkjs-examples#73]
Can you add dart code samples or websocket samples?

**Comment by aboxshall** [comment]
Hi @ashwin31, 

This is something we can look in to, one of our customers created a fantastic dart package which you could look at- https://pub.dev/packages/talkjs

As for websockets - currently we don't expose the websocket endpoints as these are used directly from within our UI. Feel free to reach out to our support if you have any follow up questions - https://talkjs.com?chat

**Comment by ashwin31** [comment]
Hi @aboxshall 

Thank you for the quick reply.

I saw the package before creating issue is github. The package developed by your customer doesn't give much flexility and control over the UI.

Am I allowed to inspect your chat UI to see websocket end points and develop custom UI ?

**Comment by eteeselink** [comment]
Hi Ashwin, Egbert here, also from TalkJS. To be frank, TalkJS does not currently make it very easy to develop a custom UI against. You can however customize the TalkJS UI quite deeply using themes, and we're close to shipping an update to this feature that lets you change it much more deeply.

While it would technically be possible to reverse engineer our websocket protocol, this is not recommended as we may change it at any time without notice.
