### ISSUE TITLE
Issue with some users receiving messages that are meant for other users

### ISSUE THREAD

**Issue by marepomana** [talkjs/talkjs-examples#75]
I have installed this visitor chat on my website and have had a number of complaints from users saying that they are receiving messages that are not intended for them. I have checked that this is the case and can see that in some instances multiple users are added to the same conversation ID

**Comment by aboxshall** [comment]
Hi Mare,

We discussed this via our livesupport and I believe we identified what the issue was; if you need any help in the future feel free to reach out to us once again.
